# --- !Ups
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  expense_id VARCHAR(64) NOT NULL,
  recipient VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS expenses (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  description VARCHAR(255),
  amount DOUBLE NOT NULL,
  paid_by VARCHAR(255) NOT NULL,
  participants TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS balances (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  from_user VARCHAR(255) NOT NULL,
  to_user VARCHAR(255) NOT NULL,
  amount DOUBLE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

# --- !Downs
DROP TABLE IF EXISTS balances;
DROP TABLE IF EXISTS expenses;
DROP TABLE IF EXISTS notifications;
