name: ExpenseSplitter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout your repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Java 17
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    # Step 3: Set up Scala and SBT
    - name: Set up Scala and SBT
      uses: olafurpg/setup-scala@v13
      with:
        java-version: '17'
        sbt-version: '1.9.5'

    # Step 4: Cache SBT dependencies
    - name: Cache sbt dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

    # Step 5: Check code formatting and style
    - name: Format and Lint
      run: sbt scalafmtCheck scalastyle

    # Step 6: Compile and run tests
    - name: Compile and Test
      run: sbt clean compile test
